version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH="/root/.pulumi/bin":$PATH
      - npm install
  build:
    commands:
      - echo "Building project..."
      - pulumi login
      - pulumi up -s dev -y
  post_build:
    commands:
      - echo "Build completed successfully!"